version: '3.8'

services:
  python:
    build: .
    container_name: ia_python
    volumes:
      - ./src:/app/src
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    working_dir: /app
    command: tail -f /dev/null